apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bl-spawning-pool
  namespace: index
spec:
  replicas:
  template:
    metadata:
      labels:
        role: bl-spawning-pool
        name: bl-spawning-pool
    spec:
      containers:
      - image: bluelens/bl-spawning-pool:latest
        name: bl-spawning-pool
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_SERVER
          value: "bl-mem-store-master"
        - name: SUBSCRIBE_TOPIC
          value: "spawn/*"
